export const cities: any = [
  { name: 'Venice', country: 'Italy' },
  { name: 'Paris', country: 'France' },
  { name: 'New York', country: 'USA' },
  { name: 'London', country: 'UK' },
  { name: 'Tokyo', country: 'Japan' },
  { name: 'Sydney', country: 'Australia' },
  { name: 'Amsterdam', country: 'Netherlands' },
  { name: 'Berlin', country: 'Germany' },
  { name: 'Barcelona', country: 'Spain' },
  { name: 'Rome', country: 'Italy' },
  { name: 'San Francisco', country: 'USA' },
  { name: 'Moscow', country: 'Russia' },
  { name: 'Dubai', country: 'United Arab Emirates' },
  { name: 'Cairo', country: 'Egypt' },
  { name: 'Rio de Janeiro', country: 'Brazil' },
  { name: 'Toronto', country: 'Canada' },
  { name: 'Seoul', country: 'South Korea' },
  { name: 'Beijing', country: 'China' },
  { name: 'Cape Town', country: 'South Africa' },
  { name: 'Buenos Aires', country: 'Argentina' },
  { name: 'Mumbai', country: 'India' },
  { name: 'Stockholm', country: 'Sweden' },
  { name: 'Helsinki', country: 'Finland' },
  { name: 'Athens', country: 'Greece' },
  { name: 'Lisbon', country: 'Portugal' },
  { name: 'Vienna', country: 'Austria' },
  { name: 'Brussels', country: 'Belgium' },
  { name: 'Dublin', country: 'Ireland' },
  { name: 'Prague', country: 'Czech Republic' },
  { name: 'Warsaw', country: 'Poland' },
  { name: 'Oslo', country: 'Norway' },
  { name: 'Budapest', country: 'Hungary' },
  { name: 'Zurich', country: 'Switzerland' },
  { name: 'Madrid', country: 'Spain' },
  { name: 'Copenhagen', country: 'Denmark' },
  { name: 'Singapore', country: 'Singapore' },
  { name: 'Kuala Lumpur', country: 'Malaysia' },
  { name: 'Bangkok', country: 'Thailand' },
  { name: 'Jakarta', country: 'Indonesia' },
  { name: 'Mexico City', country: 'Mexico' },
  { name: 'Lima', country: 'Peru' },
  { name: 'Santiago', country: 'Chile' },
  { name: 'Bogota', country: 'Colombia' },
  { name: 'Havana', country: 'Cuba' },
  { name: 'Lagos', country: 'Nigeria' },
  { name: 'Nairobi', country: 'Kenya' },
  { name: 'Johannesburg', country: 'South Africa' },
  { name: 'Sydney', country: 'Australia' },
  { name: 'Auckland', country: 'New Zealand' },
  { name: 'Wellington', country: 'New Zealand' },
  { name: 'Hobart', country: 'Australia' },
  { name: 'Melbourne', country: 'Australia' },
  { name: 'Brisbane', country: 'Australia' },
  { name: 'Perth', country: 'Australia' },
  { name: 'Adelaide', country: 'Australia' },
  { name: 'Darwin', country: 'Australia' },
  { name: 'Christchurch', country: 'New Zealand' },
  { name: 'Queenstown', country: 'New Zealand' },
  { name: 'Rotorua', country: 'New Zealand' },
  { name: 'Milan', country: 'Italy' },
  { name: 'Florence', country: 'Italy' },
  { name: 'Venice', country: 'Italy' },
  { name: 'Naples', country: 'Italy' },
  { name: 'Pisa', country: 'Italy' },
  { name: 'Verona', country: 'Italy' },
  { name: 'Bologna', country: 'Italy' },
  { name: 'Genoa', country: 'Italy' },
  { name: 'Turin', country: 'Italy' },
  { name: 'Catania', country: 'Italy' },
  { name: 'Palermo', country: 'Italy' },
  { name: 'Syracuse', country: 'Italy' },
  { name: 'Taormina', country: 'Italy' },
  { name: 'Amalfi', country: 'Italy' },
  { name: 'Capri', country: 'Italy' },
  { name: 'Rome', country: 'Italy' },
  { name: 'Milan', country: 'Italy' },
  { name: 'Florence', country: 'Italy' },
  { name: 'Venice', country: 'Italy' },
  { name: 'Naples', country: 'Italy' },
  { name: 'Pisa', country: 'Italy' },
  { name: 'Verona', country: 'Italy' },
  { name: 'Bologna', country: 'Italy' },
  { name: 'Turin', country: 'Italy' },
  { name: 'Catania', country: 'Italy' },
  { name: 'Palermo', country: 'Italy' },
  { name: 'Syracuse', country: 'Italy' },
  { name: 'Taormina', country: 'Italy' },
  { name: 'Amalfi', country: 'Italy' },
];
